server:
  port: 8986
spring:
  profiles:
    active: dev

mybatis:
  # spring boot集成mybatis的方式打印sql
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.syk.dao: debug
